modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="enhanced_swords"
version="1.0.0"
displayName="Enhanced Swords"
credits="https://discord.gg/juzUR7FAJE"
displayURL="https://discord.gg/juzUR7FAJE"
authors="The_WereF0X"

[[dependencies.enhanced_swords]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




